name: brfideliza
description: An application for businessperson.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2
  cloud_firestore: ^4.8.2
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_database: 10.2.7
  flutter_web_plugins:
    sdk: flutter
  carousel_slider: ^4.2.1
  http: ^1.1.0
  persistent_bottom_nav_bar: ^5.0.2
  mask_text_input_formatter: ^2.5.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo-brfideliza.png
